---
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: s2i-perl-run
spec:
  taskRef:
    name: s2i-perl
  outputs:
    resources:
      - name: image
        resourceRef:
          name: image
  inputs:
    resources:
      - name: source
        resourceRef:
          name: s2i-perl-ex
    params:
      - name: TLSVERIFY
        value: "false"
      - name: PATH_CONTEXT
        value: "examples/sample-test-app"
